package xyz.spigotrce.gyalang;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import xyz.spigotrce.gyalang.ast.Assignment;
import xyz.spigotrce.gyalang.ast.BinExpr;
import xyz.spigotrce.gyalang.ast.Block;
import xyz.spigotrce.gyalang.ast.CallExpr;
import xyz.spigotrce.gyalang.ast.ClassDef;
import xyz.spigotrce.gyalang.ast.Expr;
import xyz.spigotrce.gyalang.ast.ExprStmt;
import xyz.spigotrce.gyalang.ast.FuncDef;
import xyz.spigotrce.gyalang.ast.GetAttr;
import xyz.spigotrce.gyalang.ast.Identifier;
import xyz.spigotrce.gyalang.ast.IntLiteral;
import xyz.spigotrce.gyalang.ast.Param;
import xyz.spigotrce.gyalang.ast.Program;
import xyz.spigotrce.gyalang.ast.ReturnStmt;
import xyz.spigotrce.gyalang.ast.SetAttr;
import xyz.spigotrce.gyalang.ast.Stmt;
import xyz.spigotrce.gyalang.ast.StringLiteral;
import xyz.spigotrce.gyalang.ast.VarDecl;
import xyz.spigotrce.gyalang.ast.WhileStmt;

/**
 * Writes the generated bytecode to disk and runs it with the real JVM to prove
 * the produced classes are valid, verifiable, and behave as expected.
 */
class BytecodeExecutionTest {

  @TempDir Path tempDir;

  @Test
  void runsPrintProgram() throws Exception {
    Program program = mainProgram(print(new StringLiteral("hello from gylang")));

    String output = compileAndRun(program, "hello.glg");
    assertEquals("hello from gylang", output.trim());
  }

  private static Program mainProgram(Stmt... body) {
    return new Program(List.of(
        new ClassDef("Main", List.of(
            new FuncDef("main", List.of(), new Block(List.of(body)))))));
  }

  private static ExprStmt print(Expr value) {
    return new ExprStmt(new CallExpr(new Identifier("print"), List.of(value)));
  }

  private String compileAndRun(Program program, String filename) throws Exception {
    CodeGenerator gen = new CodeGenerator(filename);
    Map<String, byte[]> classes = gen.generateClasses(program);

    Path out = tempDir.resolve("classes");
    for (Map.Entry<String, byte[]> entry : classes.entrySet()) {
      Path classFile = out.resolve(entry.getKey() + ".class");
      Files.createDirectories(classFile.getParent());
      Files.write(classFile, entry.getValue());
    }

    String javaHome = System.getProperty("java.home");
    String className = gen.getClassName().replace('/', '.');

    Process process = new ProcessBuilder(
        javaHome + "/bin/java",
        "-cp", out.toString(),
        className
    ).redirectErrorStream(true).start();

    String output;
    try (InputStream is = process.getInputStream();
         ByteArrayOutputStream bos = new ByteArrayOutputStream()) {
      byte[] buf = new byte[4096];
      int n;
      while ((n = is.read(buf)) != -1) {
        bos.write(buf, 0, n);
      }
      output = bos.toString();
    }

    int exitCode = process.waitFor();
    assertEquals(0, exitCode, "JVM exited with " + exitCode + ":\n" + output);
    return output;
  }

  @Test
  void runsAssignmentMathProgram() throws Exception {
    Program program = mainProgram(
        new Assignment("x", new IntLiteral(6)),
        new Assignment("y", new BinExpr(BinExpr.Op.MUL, new IntLiteral(3), new IntLiteral(4))),
        print(new BinExpr(BinExpr.Op.ADD, new IntLiteral(0), new IntLiteral(5)))
    );

    String output = compileAndRun(program, "math.glg");
    assertEquals("5", output.trim());
  }

  @Test
  void runsWhileLoopProgram() throws Exception {
    Program program = mainProgram(
        new Assignment("x", new IntLiteral(0)),
        new WhileStmt(
            new BinExpr(BinExpr.Op.LT, new Identifier("x"), new IntLiteral(3)),
            new Block(List.of(
                print(new Identifier("x")),
                new Assignment("x",
                    new BinExpr(BinExpr.Op.ADD, new Identifier("x"), new IntLiteral(1)))
            ))
        )
    );

    String output = compileAndRun(program, "loop.glg");
    assertEquals("""
        0
        1
        2""", output.replace("\r\n", "\n").trim());
  }

  @Test
  void runsUserMethodProgram() throws Exception {
    Block addOneBody = new Block(List.of(
        new ReturnStmt(new BinExpr(BinExpr.Op.ADD, new Identifier("n"), new IntLiteral(1)))));
    FuncDef addOne = new FuncDef("add_one",
        List.of(new Param("self", "obj"), new Param("n", "obj")), addOneBody);
    Expr call = new CallExpr(
        new GetAttr(new CallExpr(new Identifier("Math"), List.of()), "add_one"),
        List.of(new IntLiteral(41)));
    Block mainBody = new Block(List.of(print(call)));
    Program program = new Program(List.of(
        new ClassDef("Math", List.of(addOne)),
        new ClassDef("Main",
            List.of(new FuncDef("main", List.of(), mainBody)))
    ));

    String output = compileAndRun(program, "func.glg");
    assertEquals("42", output.trim());
  }

  @Test
  void runsClassWithFieldsAndMethods() throws Exception {
    Program program = new Program(List.of(
        new ClassDef("Counter", List.of(
            new FuncDef("__init__",
                List.of(new Param("self", "obj"), new Param("start", "int")),
                new Block(List.of(
                    new SetAttr(new Identifier("self"), "count", new Identifier("start"), "int")))),
            new FuncDef("bump", List.of(new Param("self", "obj")),
                new Block(List.of(
                    new SetAttr(new Identifier("self"), "count",
                        new BinExpr(BinExpr.Op.ADD,
                            new GetAttr(new Identifier("self"), "count"),
                            new IntLiteral(1)), null)))),
            new FuncDef("get", List.of(new Param("self", "obj")),
                new Block(List.of(
                    new ReturnStmt(new GetAttr(new Identifier("self"), "count")))))
        )),
        new ClassDef("Main", List.of(
            new FuncDef("main", List.of(), new Block(List.of(
                new VarDecl("c", "Counter",
                    new CallExpr(new Identifier("Counter"), List.of(new IntLiteral(5)))),
                new ExprStmt(new CallExpr(new GetAttr(new Identifier("c"), "bump"), List.of())),
                print(new CallExpr(new GetAttr(new Identifier("c"), "get"), List.of())))))
        ))
    ));

    String output = compileAndRun(program, "counter.glg");
    assertEquals("6", output.replace("\r\n", "\n").trim());
  }

  @Test
  void runsPrintBuiltinCall() throws Exception {
    Program program = mainProgram(
        new Assignment("msg", new StringLiteral("variable print")),
        print(new Identifier("msg"))
    );

    String output = compileAndRun(program, "builtin_print.glg");
    assertEquals("variable print", output.trim());
  }

  @Test
  void runsLenBuiltinCall() throws Exception {
    Program program = mainProgram(
        print(new CallExpr(
            new Identifier("len"),
            List.of(new StringLiteral("hello"))
        ))
    );

    String output = compileAndRun(program, "builtin_len.glg");
    assertEquals("5", output.trim());
  }

  @Test
  void runsIntAndStrBuiltinCalls() throws Exception {
    Program program = mainProgram(
        print(new CallExpr(
            new Identifier("str"),
            List.of(new IntLiteral(42))
        )),
        print(new CallExpr(
            new Identifier("int"),
            List.of(new CallExpr(
                new Identifier("str"),
                List.of(new IntLiteral(7))
            ))
        ))
    );

    String output = compileAndRun(program, "builtin_cast.glg");
    assertEquals("42\n7", output.replace("\r\n", "\n").trim());
  }

  @Test
  void runsTypedVarDeclProgram() throws Exception {
    Program program = mainProgram(
        new VarDecl("a", "int", new IntLiteral(7)),
        print(new Identifier("a"))
    );

    String output = compileAndRun(program, "typed.glg");
    assertEquals("7", output.trim());
  }
}
